### ISSUE TITLE
Cannot find module 'cli-driver'

### ISSUE THREAD

**Issue by danielpza** [cancerberoSgx/ts-refactor#1]
Hello, I wanted to try out your module but I get an error:

```sh
$ ts-refactor fix main.ts 
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'cli-driver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/daniel/.npm-global/lib/node_modules/ts-refactor/dist/src/cli/projectDiff.js:3:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
Any ideas?

**Comment by cancerberoSgx** [comment]
Hello, just yesterday I worked on a similar problem with one dependency being broken. I just tried a fresh install and works: 

```
cd my-ts-project
npm i -D ts-refactor
npx ts-refactor organizeImports  src/main.tsx
```

Could you try re-installing it ? thanks

**Comment by danielpza** [comment]
I tried reinstalling, no luck.
btw, I install it globlally: `npm i -g ts-refactor`, I'm going to try it as a dependency to see if there's any change

**Comment by cancerberoSgx** [comment]
I was able to reproduce it on a separate linux machine, seems I had that dependency installed globally . There's a new version published that should solve the problem ts-refactor@0.0.9. Thanks and sorry for the inconvenience.

**Comment by danielpza** [comment]
Np thanks for the fix, it works now.
